### ISSUE TITLE
Error on check performing

### ISSUE THREAD

**Issue by Kaesekuchenn** [Vxrpenter/SCPToolsBot#1]
11:03:35.184 ForkJoinPool.commonPool-worker-1              RestAction      ERROR  Encountered error while processing success consumer
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:209)
        at dev.vxrp.bot.runnables.CheckNoticeOfDeparture.lambda$runNoticeOfDepartureCheck$4(CheckNoticeOfDeparture.java:44)
        at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:123)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Vxrpenter** [comment]
It's an error happening when the checker wants to find the message of the database entry but the message got deleted, will pump out a fix real fast
