### ISSUE TITLE
eco friendly wood veneer

### ISSUE THREAD

**Issue by Kaesekuchenn** [Vxrpenter/SCPToolsBot#2]
java.lang.IllegalStateException: Sending a webhook request requires the interaction to be acknowledged before expiration
        at net.dv8tion.jda.internal.entities.ReceivedMessage.lambda$getUnknownWebhookErrorMapper$4(ReceivedMessage.java:1034)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:292)
        at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:304)
        at net.dv8tion.jda.internal.requests.Requester$WorkTask.handleResponse(Requester.java:423)
        at net.dv8tion.jda.internal.requests.Requester$WorkTask.access$300(Requester.java:359)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:233)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:145)
        at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:128)
        at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:387)
        at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:477)
        at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: net.dv8tion.jda.api.exceptions.ErrorResponseException: 10015: Unknown Webhook
        at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:185)
        at net.dv8tion.jda.api.requests.Request.createErrorResponseException(Request.java:157)
        at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:290)
        ... 12 common frames omitted
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
        at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54)
        at net.dv8tion.jda.api.requests.Request.<init>(Request.java:77)
        at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:203)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:573)
        at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:539)
        at dev.vxrp.bot.events.ButtonListener.onButtonInteraction(ButtonListener.java:67)
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:463)
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:169)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:134)
        at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86)
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892)
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870)
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by Vxrpenter** [comment]
I would need some more context to replicate this

**Comment by Vxrpenter** [comment]
Closing this for now because it doesn't seem so serious
